### ISSUE TITLE
Not compatible with Arduino 1.6.4

### ISSUE THREAD

**Issue by Hackmancoltaire** [lathoub/Arduino-AppleMidi-Library#10]
Tested against newest revision. No midi messages are received by host. Recompiled the same code under 1.0.6 and things work fine.

**Comment by lathoub** [comment]
Thanks for signaling - I haven't tried with 1.6.4, but just tested it just now using IDE 1.6.5. It seems to work fine (see screenshot below). Can you check with 1.6.5?

![knipsel](https://cloud.githubusercontent.com/assets/4082369/8475657/eb91823a-20b9-11e5-99df-faf6f3ed0ad9.PNG)

**Comment by lathoub** [comment]
I tested again under 1.6.5 and all works fine - have you tested under 1.6.5?

**Comment by Hackmancoltaire** [comment]
I'm in the process of testing. Within the next few days I'll have an answer.

**Comment by Hackmancoltaire** [comment]
Confirmed broken on Mac 1.6.5. Compiled master branch as of today under 1.0.6 and it works fine.

**Comment by Hackmancoltaire** [comment]
There seems to be a problem with the session connection. I see packets in Wireshark as the host invites, the Arduino accepts, then it does it over again
![screen shot 2015-07-20 at 5 17 26 pm](https://cloud.githubusercontent.com/assets/341149/8790473/3bcbff8a-2f03-11e5-99ab-58c31ccf199b.png)

**Comment by Hackmancoltaire** [comment]
Ok, scratch that. Had a configuration issue. Seems to work.
