### ISSUE TITLE
Donde encuentro la RAMA FEAT?

### ISSUE THREAD

**Issue by alomdj00** [lathoub/Arduino-AppleMIDI-Library#102]
Hola, he leido en otras preguntas que nombran la rama FEAT, sin embargo no se ha que libreria pertenece, he buscado esta rama aqui en appleMidi, y tambien en fortyseveneffects, sin embargo no logro dar con ella, no se si fue borrada o si pertenece a otro repositorio.
Si pudieran aclararme donde encuentro o descargo la rama Feat, muchas gracias

**Comment by lathoub** [comment]
@alomdj00 thank you for engagement, but please consider to use the english language (free translators exist on the web: using google translate or deepl - i have to do the same to understand your question, and many other who wouldl like to learn from your question). It does not have to be formulated perfectly (I'm also not a native English speaker), output from a translator works most of the time.

Also, please consider using the [Discussion section](https://github.com/lathoub/Arduino-AppleMIDI-Library/discussions) for 'open questions / discussions'

To answer your question: I have no clue where you found FEAT - try to describe what you are trying to achive (in Discussions)
