### ISSUE TITLE
loses connection after 1 or 2 minutes (with a mac)

### ISSUE THREAD

**Issue by folkertvanheusden** [lathoub/Arduino-AppleMIDI-Library#131]
## Context

- What board are you using ?
   wemos d1 esp32
   W5500 ethernet shield
- What version of the Arduino IDE are you using ?
    -  platformio
- What Operating System are you using for the DAW
    - [X]  Linux
- Is your problem related to:
    - [ ]  Setup
    - [ ]  Connecting
    - [X]  AppleMIDI <> MIDI
    - [?]  Dropped messages
- How comfortable are you with code ?
    - [ ]  Complete beginner
    - [ ]  I've done basic projects
    - [ ]  I know my way around C/C++
    - [X]  Advanced / professional

## Describe your project and what you expect to happen:

As a test of a W5500 setup I took the example-code for the ESP32/W5500 combination.
I enabled all logging and added a tiny bit of code to show the millis() for each logged line.

## Describe your problem (what does not work):

I "boot" the wemos and let a Mac (macos x 10.7) connect to it via the midi-panel. Everything is connected directly via the same gigabit ethernet switch.

Now after a while (around 1 or 2 minutes) the communication stops with a timeout (the mac complains about that). After that, communication cannot be restarted (unless I reset the esp).

## Steps to reproduce

I'll include my modified version and a logfile showing what is happening.

[problem.zip](https://github.com/lathoub/Arduino-AppleMIDI-Library/files/7060137/problem.zip)

**Comment by lathoub** [comment]
@folkertvanheusden, any update on this issue?

**Comment by folkertvanheusden** [comment]
Hi,

No update yet, I've been busy with other things.

**Comment by lathoub** [comment]
@folkertvanheusden, i'm about to make this as stale, you can always reopen
