### ISSUE TITLE
SysEx

### ISSUE THREAD

**Issue by DBrenchley** [lathoub/Arduino-AppleMidi-Library#28]
Good day gents ..
Do I assume correctly, implementation of support for SysEx is not yet complete?
I'm attempting a "dump" .. response "decode_sysex_start" ..
pouring though the code seems to reveal a work in progress ..

**Comment by Hackmancoltaire** [comment]
It is a bit.

**Comment by DBrenchley** [comment]
Thanks .. I'll await further updates!!

**Comment by mathieu-b** [comment]
Any news?
Cheers.

**Comment by lathoub** [comment]
I have **started** coding SysEx (first step).

Sending SysEx from the Arduino seems to work - can someone check (see sample code).
(Some code is still hardcoded and needs a beauty makeover.)

**Comment by lathoub** [comment]
I modified the code so that it can now receive SysEx buffers.
Its up to the receiver to decode the buffer further (update SysEx sample code)

**Comment by lathoub** [comment]
Added support for 1) Full SysEx messages and 2) SysEx Segments (when message is larger than 255 bytes). See updated sample
