### ISSUE TITLE
Serial Interface for AppleMidi

### ISSUE THREAD

**Issue by trlafleur** [lathoub/Arduino-AppleMidi-Library#37]
Being able to use one stack for both WiFi and Serial (Hardwired Midi) would be a bonus.

Adding a serial driver to this stack would be very useful addition. Data from the interfaces could be OR together, or selected in real-time by an API option...

This option could also be use as a hardwired Midi to WiFi interface tool.

**Comment by lathoub** [comment]
Not sure if this should be part of the core of the library. The above can be achieved using a sketch that has both a MIDI and AppleMIDI interface. Hook the events from AppleMIDI to send to MIDI and similar for MIDI to AppleMIDI.

The above would make a good example to be included.
