### ISSUE TITLE
Not functional with Arduino Ethernet

### ISSUE THREAD

**Issue by DatanoiseTV** [lathoub/Arduino-AppleMidi-Library#38]
<img width="786" alt="applemidi_errors" src="https://cloud.githubusercontent.com/assets/6614616/17838311/e215a6d8-67ca-11e6-8e9b-18b604c025f4.png">

Unfortunately it seems no longer work / or has issues with Arduino Ethernet.
The connection from OSX times out, but firewall etc. is off and the Arduino Ethernet is
on the same network.

**Comment by DatanoiseTV** [comment]
My current guess is that the Arduino Ethernet might be running out of memory? It has only 2KB or KB RAM as far as I remember.

**Comment by lathoub** [comment]
Correct, the current version is too large for Arduino Ethernet.

**Comment by lathoub** [comment]
I've tested the `NoteOnOffEverySec ` on an `Arduino Ethernet `today and mem usage was:

```
Sketch uses 24002 bytes (74%) of program storage space. Maximum is 32256 bytes.
Global variables use 969 bytes (47%) of dynamic memory, leaving 1079 bytes for local variables. Maximum is 2048 bytes.
```
