### ISSUE TITLE
Arduino-AppleMIDI-Library also works on ESP32

### ISSUE THREAD

**Issue by JorenSix** [lathoub/Arduino-AppleMIDI-Library#48]
Not really an issue, more of a feature: I just tested the ESP8266 Note On Note Off example on an ESP 32 and it works out of the box. Only one small change is needed  `#include <ESP8266WiFi.h>` needs to be replaced with  `#include <WiFi.h>`. 

I tested this with an ESP32 Thing with the latest git versions.

Thanks for the effort!

**Comment by lathoub** [comment]
Thanks @JorenSix - that is good news!
I'm not familiar with the ESP32, but nice to hear that the ESP8266 demo works, with a minor modification.

How about you create a new example for the ESP32 (in the Examples dir) and include it in a pull request?
(That way you get the credits for the example)
