### ISSUE TITLE
[ESP8266 Wifi Shield] Data received is too short for parsing!

### ISSUE THREAD

**Issue by rinaldohack** [lathoub/Arduino-AppleMIDI-Library#58]
I was using this library with ESP8266 as Wifi shield replacement. It is ESP-01 module. 

I can receive MIDI  from my computer and it is printed on serial monitor. But NoteOnOff every second isn't received by Ableton Live. 
I turned on debugging in rtpMIDI by Tobias Erichsen, and I got this error : 

`[   184212.185] rtpMIDI_1_1_8_240 [ DIAG_ERROR   ]: DESKTOP-G2JHTG2: Data received is too short for parsing!`

This question also on [stackexchange ](https://arduino.stackexchange.com/questions/56381/how-do-i-send-midi-using-rtpmidi-on-arduino-mega-esp8266), and [here is my full code so far](https://pastebin.com/nbBJ5dHu). Also [here is my verbose log.](https://pastebin.com/wZsqWuu6)

**Comment by lathoub** [comment]
(Assuming you are using the latest release 1.5.4)
Did you try to run the example "Esp8266_NoteOnOffEverySec" that comes in the current release - as is? It looks like you are using different header from the example. (you use WifiEsp library by bportaluri, why? I used ESP8266Wifi.h without any problem, see header of the example)

```
#include <ESP8266WiFi.h>
#include <WiFiClient.h>
#include <WiFiUdp.h>
```

I have to admit, its been a while since I used an Esp8266, so maybe things have changed.

**Comment by rinaldohack** [comment]
Because thats the first library that worked for me. 

I'm going home now, and going to try ESP8266WiFi.h ASAP. Will update here. 
Thanks!

**Comment by rinaldohack** [comment]
Oh and also, 1.5.4 isnt available on arduino library manager yet. 
I used that, but manually installed it. You might want to take a look.

**Comment by rinaldohack** [comment]
> (Assuming you are using the latest release 1.5.4)
> Did you try to run the example "Esp8266_NoteOnOffEverySec" that comes in the current release - as is? It looks like you are using different header from the example. (you use WifiEsp library by bportaluri, why? I used ESP8266Wifi.h without any problem, see header of the example)
> 
> ```
> #include <ESP8266WiFi.h>
> #include <WiFiClient.h>
> #include <WiFiUdp.h>
> ```
> I have to admit, its been a while since I used an Esp8266, so maybe things have changed.

I just realized your library is for running in esp8266 without any additional microcontrollers. 
I'm using esp as wifi shield alternative, using Arduino Mega.

**Comment by lathoub** [comment]
Good that it worked directly to ESP8266.
I just ordered an ESP8266 Wifi shield as well, so I can try as well.

From the limited info (and no experience with it at all), I believe the issue might be in the ::internalSend methods - in particular how they translate in the AT commands.

Did you try to Wireshark the outgoing bytes?

**Comment by lathoub** [comment]
(from the limited info)
I believe the issue is in how [https://github.com/bportaluri/WiFiEsp](url) translates/maps the UDP write commands to AT commands.

Check the `internalSend` methods in `AppleMidi.hpp`

**Comment by rinaldohack** [comment]
> (from the limited info)
> I believe the issue is in how [https://github.com/bportaluri/WiFiEsp](url) translates/maps the UDP write commands to AT commands.
> 
> Check the `internalSend` methods in `AppleMidi.hpp`

if I had to report this to WifiEsp dev, what do I need to say?
or is there any workaround that you might know?

**Comment by lathoub** [comment]
How about you put some debug messages in `WiFiEspUdp.h` of the `WiFiEsp` to see what is transmitted.

**Comment by rinaldohack** [comment]
I don't have enough knowledge for this. Please put this on hold for a while.

Now, I'm storing the ssid, pass, and session name in Arduino Mega. then I programmed the ESP8266 directly, but wait for the serial to receive wifi name from mega first. Totally different approach.

**Comment by sjc-or** [comment]
Still doesn't work with WiFiEsp. I also tried sending long Sysex messaage so I don't believe packetsize is the answer.  I can use their example to send UDP messages to a time server so I know UDP message output WiFiEspUdp is working.

Just can't figure out out to get any type of message to AppleMIDI.
Will try to capture what is being sent but I'm really new to both the AppleMIDI and WiFIEsp code.
