### ISSUE TITLE
'Signature not supported' message

### ISSUE THREAD

**Issue by AnalogDave** [lathoub/Arduino-AppleMidi-Library#6]
Found your library and have being playing around for a coupe of days and think I have discovered a bug? This seems like a great library and keen to understand if I'm doing something wrong or found a bug.

In the debug mode I'm getting the following output.
![arduino log image](https://cloud.githubusercontent.com/assets/8555161/4042819/b161752a-2d08-11e4-8003-6c7f62456e1d.png)

My code is very simple (based on the sample provided) and sending a midi noteOn (90 00 7f) when it receives a noteOn (90 00 00). I have tried both send the noteOn message in the OnAppleMidiNoteOn callback and outside the callback. My plan is to build a HUI emulator and keen to get the HUI protocol ping working.

Wireshark log below (never used this tool before so hope everything looks alright)
![wireshark log image](https://cloud.githubusercontent.com/assets/8555161/4042865/512830f8-2d09-11e4-9865-93733f51616e.jpg)

You'll note that I'm using a virtual Keyboard to send the initial noteOn message and therefore the keyboard is also sending a note off message which pro tools doesn't do.

Thanks for your help
Dave

**Comment by lathoub** [comment]
accepted pull request
