### ISSUE TITLE
[no issue] Connect to a remote session

### ISSUE THREAD

**Issue by emu1701** [lathoub/Arduino-AppleMIDI-Library#70]
Hi, 

I am trying to establish a two way communication between 2 ESPs. One initiates a session. 
The other one should join (connect to) this session to exchange events. 
The communication should be wireless. 

Both ESPs connect to each other and can talk to each other (I tested this via a Webserver/HTTPClient). The "Server" ESP instances a session. The problem is I don't know how to tell the second ESP to connect to this session. 

is there any example that shows how to join a remote session? Or can you provide sample code?

Thanks

**Comment by luyfigue** [comment]
You can use the `invite` method:
https://github.com/lathoub/Arduino-AppleMIDI-Library/blob/master/src/AppleMidi.h#L89
e.g:
`AppleMIDI.invite(IPAddress(192,168,0,2), 5004);`

**Comment by luyfigue** [comment]
Actually there is an example here:
https://github.com/lathoub/Arduino-AppleMIDI-Library/blob/master/examples/EthernetShield_InitiateSession/EthernetShield_InitiateSession.ino#L56
The other end just needs to do the `AppleMIDI.begin("xyz");`

**Comment by emu1701** [comment]
Sorry for the late answer. I wasn't able to access my computer the last days. 

Your solution works perfectly. 

Thanks a lot
