### ISSUE TITLE
the Lib does not handle RPN or NRPN messages

### ISSUE THREAD

**Issue by designerfuzzi** [lathoub/Arduino-AppleMIDI-Library#72]
as midi via network is usually used to get midi feedback from studio mixers with lots of parameters wondering why NRPN && RPN is not prepared to be recognized from this library. 
In other words, any networked midi stream containing RPN or NRPN messages will mess up the buffer and treated as normal CC and vice versa. 
You will have to implement LSB && MSB encoding and decoding (bit shifting) and distinguish Control Change Messages from RPN or NRPN with its corresponding LSB/MSB data pairs almost same as you would do for pitch-wheel data.

another thing.. 
Active-sensing should have a timeout to shut down the connection if not received in between 300ms after the last signal.  If it is implemented without timer it is not needed at all, because a stream would stay valid until manually shut down.

**Comment by designerfuzzi** [comment]
same for bank-select, one of the most common messages apart from notes and CC.

**Comment by lathoub** [comment]
Thanks for the comments, branch [feat/2.0.0](https://github.com/lathoub/Arduino-AppleMIDI-Library/tree/feat/2.0.0) uses the MIDI parser from [47effects](https://github.com/FortySevenEffects/arduino_midi_library) that supports RPN and NRPN. All

feat/2.0.0 isn't fully ready, would be great if you could test

**Comment by lathoub** [comment]
@designerfuzzi active-Sensing added to MIDI parser
More features added that need testing. Please check [https://github.com/lathoub/Arduino-AppleMIDI-Library/tree/feat/2.0.0](url)

**Comment by designerfuzzi** [comment]
amazing.. nice done!
